"""Pre-commit hook generator for Lazarus protocol enforcement.

Generates a shell script that runs the domain's audit module
as a git pre-commit hook.
"""


def generate_pre_commit_script(
    audit_module: str = "engine.audit",
    trigger_dirs: list[str] | None = None,
) -> str:
    """Generate a pre-commit hook shell script.

    Args:
        audit_module: Python module to run (e.g. 'engine.audit')
        trigger_dirs: directories that trigger the audit (e.g. ['enums/', 'data/'])
    """
    if trigger_dirs is None:
        trigger_dirs = ["enums/", "data/"]

    dir_checks = " || ".join(
        f'echo "$STAGED" | grep -q "^{d}"' for d in trigger_dirs
    )

    return f"""#!/bin/sh
# Lazarus Protocol — Pre-commit audit hook
# Auto-generated by lazarus.hooks.pre_commit
# Install: cp this-file .git/hooks/pre-commit && chmod +x .git/hooks/pre-commit

STAGED=$(git diff --cached --name-only)

# Only run audit if relevant files are staged
if {dir_checks}; then
    echo "Running Lazarus audit on staged changes..."
    python -m {audit_module} --staged
    EXIT_CODE=$?
    if [ $EXIT_CODE -ne 0 ]; then
        echo ""
        echo "[STOP] Audit failed. Commit blocked."
        echo "Fix violations and try again."
        exit 1
    fi
    echo "Audit passed."
fi

exit 0
"""
